Fix TFSec CI step

diff --git a/.github/actions/tfsec/action.yaml b/.github/actions/tfsec/action.yaml
--- a/.github/actions/tfsec/action.yaml
+++ b/.github/actions/tfsec/action.yaml
@@ -6,12 +6,11 @@ runs:
     - name: "TFSec Scan - Components"
       shell: bash
       run: |
-        for component in $(find infrastructure/terraform/components -mindepth 1 -type d); do
-          scripts/terraform/tfsec.sh $component
-        done
-    - name: "TFSec Scan - Modules"
-      shell: bash
-      run: |
-        for module in $(find infrastructure/terraform/modules -mindepth 1 -type d); do
-          scripts/terraform/tfsec.sh $module
-        done
+        modules_exit_code=0
+
+        ./scripts/terraform/tfsec.sh ./infrastructure/modules || modules_exit_code=$?
+
+        if [ $modules_exit_code -ne 0 ]; then
+          echo "One or more TFSec scans failed."
+          exit 1
+        fi
